# The telemetry section defines parameters for Hermes' built-in telemetry capabilities. Global section has parameters that apply globally to the relayer operation.
[global]

# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'trace'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 101
clear_on_start = true
tx_confirmation = true


[rest]
enabled = true
host = '0.0.0.0'
port = 6969

[telemetry]

enabled = true
host = '0.0.0.0'
port = 9696


[[chains]]
id = 'theta-testnet-001'
rpc_addr = 'http://51.195.63.75:26657'
grpc_addr = 'http://51.195.63.75:9090'
websocket_addr = 'ws://51.195.63.75:26657/websocket'
rpc_timeout = '15s'
account_prefix = 'cosmos'
key_name = 'gaia'
#address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'
default_gas = 2000000
max_gas = 10000000
gas_price = { price = 0.00, denom = 'uatom' }
gas_multiplier = 1.1
max_msg_num = 25
max_tx_size = 180000
clock_drift = '10s'
max_block_time = '15s'
trusting_period = '2h'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'B-Harvest'
[chains.packet_filter]
policy = 'allow'
list = [
 ['transfer', 'channel-1286'],
]
#fee_granter = ''


[[chains]]
id = 'mooncat-2-external'
rpc_addr = 'http://51.195.63.75:16657'
grpc_addr = 'http://51.195.63.75:19090'
websocket_addr = 'ws://51.195.63.75:16657/websocket'
rpc_timeout = '15s'
account_prefix = 'cre'
key_name = 'crescent'
store_prefix = 'ibc'
default_gas = 3000000
max_gas = 10000000
gas_price = { price = 0.00, denom = 'ucre' }
gas_multiplier = 1.2
max_msg_num = 30
max_tx_size = 1800000
clock_drift = '10s'
trusting_period = '2h'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'B-Harvest'
[chains.packet_filter]
policy = 'allow'
list = [
 ['transfer', 'channel-25'],
]
# fee_granter = ''